---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-secrets-provider-for-k8s-sidecar
type: Opaque
data:
stringData:
  conjur-map: |-
    spring.datasource.username: data/bnl/ocp-apps/username
    spring.datasource.password: data/bnl/ocp-apps/password
    spring.datasource.url: data/bnl/ocp-apps/url