---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authn-k8s-sa
  labels:
    app.kubernetes.io/name: "conjur-serviceaccount"
    app.kubernetes.io/component: "conjur-kubernetes-identity"
    app.kubernetes.io/instance: "conjur-serviceaccount"
    app.kubernetes.io/part-of: "conjur-config"
    conjur.org/name: "conjur-serviceaccount"
---
apiVersion: v1
kind: Secret
metadata:
  name: authn-k8s-sa-service-account-token
  labels:
    app.kubernetes.io/name: "conjur-serviceaccount-token"
    app.kubernetes.io/component: "conjur-kubernetes-identity"
    app.kubernetes.io/instance: "conjur-serviceaccount"
    app.kubernetes.io/part-of: "conjur-config"
    conjur.org/name: "conjur-serviceaccount-token"
  annotations:
    kubernetes.io/service-account.name: authn-k8s-sa
type: kubernetes.io/service-account-token



---
# Source: conjur-config-cluster-prep/templates/clusterrole.yaml
# This ClusterRole defines the Kubernetes API access permissions that the Conjur
# authenticator will require in order to validate application identities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "conjur-clusterrole"
  labels:
    app.kubernetes.io/name: "conjur-clusterrole"
    app.kubernetes.io/component: "conjur-permissions"
    app.kubernetes.io/instance: "conjur-clusterrole"
    app.kubernetes.io/part-of: "conjur-config"
    conjur.org/name: "conjur-clusterrole"

rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "serviceaccounts"]
    verbs: ["get", "list"]
  - apiGroups: ["extensions"]
    resources: [ "deployments", "replicasets"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: [ "deployments", "statefulsets", "replicasets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: conjur-authn-rolebinding
  namespace: $CYBERARK_CONJUR_NAMESPACE
subjects:
  - kind: ServiceAccount
    name: "authn-k8s-sa"
    namespace: $CYBERARK_CONJUR_NAMESPACE
roleRef:
  kind: ClusterRole
  name: "conjur-clusterrole"
  apiGroup: rbac.authorization.k8s.io